// Centralized host patterns for:
// - MV3 `host_permissions` (wxt manifest)
// - Content script `matches` (pumpfun.content)
//
// Keep in sync with platform adapters' `hostPattern` arrays.

export const PLATFORM_HOST_PATTERNS = [
  '*://pump.fun/*',
  '*://amm.pump.fun/*',
  '*://swap.pump.fun/*',
  '*://raydium.io/*',
  '*://letsbonk.fun/*',
  '*://bonk.fun/*',
  '*://moonshot.money/*',
  '*://dexscreener.com/*',
  '*://www.dexscreener.com/*',
  '*://birdeye.so/*',
  '*://bags.fm/*',
  '*://solscan.io/*',
  '*://*.solscan.io/*',
  '*://www.dextools.io/*',
  '*://dextools.io/*',
  '*://dex.coinmarketcap.com/*',
  '*://www.coingecko.com/*',
  '*://app.uniswap.org/*',
  '*://pancakeswap.finance/*',
  '*://www.pancakeswap.finance/*',
  '*://aerodrome.finance/*',
  '*://www.aerodrome.finance/*',
  '*://etherscan.io/*',
  '*://www.etherscan.io/*',
  '*://bscscan.com/*',
  '*://www.bscscan.com/*',
  '*://basescan.org/*',
  '*://www.basescan.org/*',
  '*://gopluslabs.io/*',
  '*://www.gopluslabs.io/*',
  '*://tokensniffer.com/*',
  '*://www.tokensniffer.com/*',
  '*://honeypot.is/*',
  '*://www.honeypot.is/*',
  '*://geckoterminal.com/*',
  '*://www.geckoterminal.com/*',
  '*://ave.ai/*',
  '*://www.ave.ai/*',
  '*://dexview.com/*',
  '*://www.dexview.com/*',
  '*://www.sushi.com/*',
  '*://sushi.com/*',
  '*://app.1inch.io/*',
  '*://matcha.xyz/*',
  '*://www.matcha.xyz/*',
  '*://swap.cow.fi/*',
  '*://app.paraswap.io/*',
  '*://www.paraswap.io/*',
  '*://baseswap.fi/*',
  '*://www.baseswap.fi/*',
  '*://flaunch.gg/*',
  '*://www.flaunch.gg/*',
  '*://four.meme/*',
  '*://www.four.meme/*',
  '*://gmgn.ai/*',
  '*://www.gmgn.ai/*',
  '*://poocoin.app/*',
  '*://www.poocoin.app/*',
  '*://app.virtuals.io/*',
  '*://www.virtuals.io/*',
  '*://virtuals.io/*',
  '*://debank.com/*',
  '*://www.debank.com/*',
  '*://app.zerion.io/*',
  '*://zerion.io/*',
  '*://www.zerion.io/*',
] as const;

