import { REQUEST_TIMEOUT_MS } from './api-client';

export const POPUP_DEFAULT_MESSAGE_TIMEOUT_MS = 2500;
export const POPUP_AUTH_REQUEST_TIMEOUT_MS = REQUEST_TIMEOUT_MS + 3000;
export const POPUP_ANALYZE_REQUEST_TIMEOUT_MS = REQUEST_TIMEOUT_MS + 3000;
